

# 基于 RFM 的 P2P 用户聚类模型

### 22.3.1 获取数据

In [9]:
# 导入需要的库，并读取 csv 文件。

import pandas as pd
data = pd.read_csv('data.csv', encoding = 'utf-8') 

data.head(5)

           ID  RECENT_DATE  TRANS_NUM  AVG_TRANS_AMT  TRANS_NUM_BEFORE
0  4356689447     20180125        NaN            0.0               0.0
1  5985727751     20180125        0.0            0.0               NaN
2  8221439519     20171211        0.0            0.0               0.0
3  6255360379     20171226        0.0            0.0               0.0
4  5985726631     20171203        0.0            0.0               0.0

### 22.3.2 数据预处理

In [10]:
# 过滤掉用户 ID 为空的用户投资记录。

data = data[data['ID'].notnull()]

# 投资金额或投资次数为空值，统一修正为 0。

data = data.fillna(0)

# 保存清洗后的数据。

data.to_csv('clean_data.csv') 

data.head(5)

           ID  RECENT_DATE  TRANS_NUM  AVG_TRANS_AMT  TRANS_NUM_BEFORE
0  4356689447     20180125        0.0            0.0               0.0
1  5985727751     20180125        0.0            0.0               0.0
2  8221439519     20171211        0.0            0.0               0.0
3  6255360379     20171226        0.0            0.0               0.0
4  5985726631     20171203        0.0            0.0               0.0

### 22.3.3.	计算 RFM 指标

In [37]:
# 读入清洗后的用户投资数据。

data = pd.read_csv('clean_data.csv', encoding = 'utf-8')

# 标记流失用户和沉默用户。

data['RFM'] = ''   
data['USR_TYPE'] = ''

# 流失用户 ( L ) 即为观测时间前曾有投资交易记录，但观测时间段内无投资记录的用户。

data.ix[(data.TRANS_NUM_BEFORE > 0) & (data.TRANS_NUM == 0),['USR_TYPE']] = 'L'    
data.ix[(data.TRANS_NUM_BEFORE > 0) & (data.TRANS_NUM == 0),['RFM']] = '000'

# 沉默用户 ( S ) 即为注册开户至今，从未有过任何一笔投资交易记录的用户。

data.ix[(data.TRANS_NUM_BEFORE == 0) & (data.TRANS_NUM == 0),['USR_TYPE']] = 'S'
data.ix[(data. TRANS_NUM_BEFORE == 0) & (data.TRANS_NUM == 0),['RFM']] = '000'

# 计算最近交易时间距离 2018 年 2 月 14 日的天数。

data['DAYS'] =  [(pd.to_datetime('02/14/2018')- pd.to_datetime(str(t))).days 
                   for t in data['RECENT_DATE']] 


# 计算观测窗内有投资交易记录的用户的 R,F,M 指标。

data['R'] = data[data.TRANS_NUM > 0]['DAYS']
data['F'] = data[data.TRANS_NUM > 0]['TRANS_NUM']
data['M'] = data[data.TRANS_NUM > 0]['AVG_TRANS_AMT']

# 筛选有效 R,F,M 指标存入单独 dataframe，用于后续建立模型。

data_RFM = data[['R','F','M']].dropna()

data

,Unnamed: 0,ID,RECENT_DATE,TRANS_NUM,AVG_TRANS_AMT,TRANS_NUM_BEFORE,RFM,USR_TYPE,DAYS,R,F,M
0,0,4356689447,20180125,0.0,0.000000e+00,0.0,000,S,20,NaN,NaN,NaN
1,1,5985727751,20180125,0.0,0.000000e+00,0.0,000,S,20,NaN,NaN,NaN
2,2,8221439519,20171211,0.0,0.000000e+00,0.0,000,S,65,NaN,NaN,NaN
3,3,6255360379,20171226,0.0,0.000000e+00,0.0,000,S,50,NaN,NaN,NaN
4,4,5985726631,20171203,0.0,0.000000e+00,0.0,000,S,73,NaN,NaN,NaN
5,5,6255360403,20180109,0.0,0.000000e+00,0.0,000,S,36,NaN,NaN,NaN
6,6,8221440591,20171208,0.0,0.000000e+00,0.0,000,S,68,NaN,NaN,NaN
7,7,8221439459,20171208,0.0,0.000000e+00,1.0,000,L,68,NaN,NaN,NaN
8,8,4373540587,20171204,0.0,0.000000e+00,0.0,000,S,72,NaN,NaN,NaN
9,9,8221438327,20171122,0.0,0.000000e+00,0.0,000,S,84,NaN,NaN,NaN
10,10,8221438387,20171123,0.0,0.000000e+00,0.0,000,S,83,NaN,NaN,NaN
11,11,6255358175,20180206,0.0,0.000000e+00,0.0,000,S,8,NaN,NaN,NaN
12,12,4373539491,20180210,0.0,0.000000e+00,0.0,000,S,4,NaN,NaN,NaN
13,13,6255359199,20180126,0.0,0.000000e+00,0.0,000,S,19,NaN,NaN,NaN
14,14,5137506867,20180210,0.0,0.000000e+00,0.0,000,S,4,NaN,NaN,NaN
15,15,5137506855,20180129,207.0,0.000000e+00,138.0,,,16,16.0,207.0,0.000000e+00
16,16,6851792819,20171125,0.0,0.000000e+00,0.0,000,S,81,NaN,NaN,NaN
17,17,4362308131,20180131,24.0,5.302320e+05,84.0,,,14,14.0,24.0,5.302320e+05
18,18,7446429015,20180210,0.0,0.000000e+00,0.0,000,S,4,NaN,NaN,NaN
19,19,8491076627,20171128,1.0,5.000000e+04,0.0,,,78,78.0,1.0,5.000000e+04
20,20,4362703403,20171205,0.0,0.000000e+00,0.0,000,S,71,NaN,NaN,NaN
21,21,8491075519,20180201,20.0,4.966667e+04,0.0,,,13,13.0,20.0,4.966667e+04
22,22,8221435907,20171211,0.0,0.000000e+00,0.0,000,S,65,NaN,NaN,NaN
23,23,4334214987,20180130,48.0,4.800000e+04,36.0,,,15,15.0,48.0,4.800000e+04
24,24,4362301135,20171122,0.0,0.000000e+00,0.0,000,S,84,NaN,NaN,NaN
25,25,7103577783,20180115,27.0,5.400000e+04,63.0,,,30,30.0,27.0,5.400000e+04
26,26,6339286107,20180125,0.0,0.000000e+00,0.0,000,S,20,NaN,NaN,NaN
27,27,5985721899,20180120,0.0,0.000000e+00,6.0,000,L,25,NaN,NaN,NaN
28,28,4412856783,20180123,0.0,0.000000e+00,0.0,000,S,22,NaN,NaN,NaN
29,29,4356682487,20180202,0.0,0.000000e+00,95.0,000,L,12,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
970,970,8142865064,20180125,0.0,0.000000e+00,0.0,000,S,20,NaN,NaN,NaN
971,971,4519660412,20180201,0.0,0.000000e+00,0.0,000,S,13,NaN,NaN,NaN
972,972,4339903456,20180125,0.0,0.000000e+00,0.0,000,S,20,NaN,NaN,NaN
973,973,4339903444,20180106,360.0,9.391169e+06,640.0,,,39,39.0,360.0,9.391169e+06
974,974,8142864968,20171116,0.0,0.000000e+00,0.0,000,S,90,NaN,NaN,NaN
975,975,4356749864,20180125,0.0,0.000000e+00,0.0,000,S,20,NaN,NaN,NaN
976,976,4519653416,20180210,0.0,0.000000e+00,0.0,000,S,4,NaN,NaN,NaN
977,977,9260714012,20180202,0.0,0.000000e+00,0.0,000,S,12,NaN,NaN,NaN
978,978,4334280196,20180125,0.0,0.000000e+00,0.0,000,S,20,NaN,NaN,NaN
979,979,5637509252,20171222,6.0,0.000000e+00,10.0,,,54,54.0,6.0,0.000000e+00
980,980,4373601088,20180211,0.0,0.000000e+00,0.0,000,S,3,NaN,NaN,NaN
981,981,8400011508,20180207,0.0,0.000000e+00,0.0,000,S,7,NaN,NaN,NaN
982,982,4519652332,20180208,0.0,0.000000e+00,0.0,000,S,6,NaN,NaN,NaN
983,983,4519652236,20180129,0.0,0.000000e+00,0.0,000,S,16,NaN,NaN,NaN
984,984,4345512736,20180129,42.0,0.000000e+00,39.0,,,16,16.0,42.0,0.000000e+00
985,985,7076787248,20180116,2.0,1.024800e+04,2.0,,,29,29.0,2.0,1.024800e+04
986,986,4351130192,20180205,7.0,1.050000e+04,28.0,,,9,9.0,7.0,1.050000e+04
987,987,4362690608,20180210,0.0,0.000000e+00,0.0,000,S,4,NaN,NaN,NaN
988,988,7025003460,20171207,0.0,0.000000e+00,12.0,000,L,69,NaN,NaN,NaN
989,989,8142860464,20180125,0.0,0.000000e+00,0.0,000,S,20,NaN,NaN,NaN
990,990,8142860452,20171205,0.0,0.000000e+00,0.0,000,S,71,NaN,NaN,NaN
991,991,8142861488,20180204,0.0,0.000000e+00,0.0,000,S,10,NaN,NaN,NaN
992,992,6296435832,20180125,0.0,0.000000e+00,0.0,000,S,20,NaN,NaN,NaN
993,993,5907146384,20171218,0.0,0.000000e+00,0.0,000,S,58,NaN,NaN,NaN
994,994,4328664004,20180129,495.0,0.000000e+00,975.0,,,16,16.0,495.0,0.000000e+00
995,995,7025003388,20180125,0.0,0.000000e+00,0.0,000,S,20,NaN,NaN,NaN
996,996,4328664896,20180210,0.0,0.000000e+00,0.0,000,S,4,NaN,NaN,NaN
997,997,8400005728,20171212,0.0,0.000000e+00,0.0,000,S,64,NaN,NaN,NaN
998,998,8142859248,20180129,20.0,0.000000e+00,6.0,,,16,16.0,20.0,0.000000e+00
999,999,4339898772,20180129,343.0,0.000000e+00,365.0,,,16,16.0,343.0,0.000000e+00

## 22.3.4.	数据标准化

In [38]:
from sklearn import preprocessing
from pandas import DataFrame

min_max_scaler = preprocessing.MinMaxScaler()
data_minmax = pd.DataFrame(min_max_scaler.fit_transform(data_RFM),
                           columns = ['R','F','M'])

# 零均值标准化。
data_scale = pd.DataFrame(preprocessing.scale(data_RFM),
                          columns = ['R','F','M']) 

data_scale

            R         F         M
0   -0.481776 -0.117034 -0.189368
1   -0.579722 -0.193889 -0.156358
2    2.554565 -0.203548 -0.186256
3   -0.628696 -0.195569 -0.186276
4   -0.530749 -0.183809 -0.186380
5    0.203849 -0.192629 -0.186007
6   -0.481776 -0.022540 -0.189368
7   -1.069455 -0.093095 -0.159314
8    0.693582 -0.202708 -0.188024
9    1.183314  0.123611 -0.185119
10   0.350769 -0.193469 -0.120111
11  -0.579722 -0.202288 -0.189368
12  -0.481776  0.798507 -0.189368
13   0.154876 -0.190529 -0.189368
14  -1.118428 -0.090575 -0.058631
15  -1.118428 -0.203548 -0.189182
16   0.987421 -0.188009 -0.189368
17  -0.187937 -0.203548 -0.189182
18   2.652511 -0.167010 -0.183890
19   1.379207 -0.203548 -0.189337
20  -1.020482 -0.166170 -0.159784
21  -0.971508  0.582221 -0.109233
22  -0.334856 -0.202288 -0.178162
23   1.183314 -0.203548 -0.187501
24  -0.971508  3.984003  2.900660
25   0.105903 -0.198928 -0.180590
26   0.007956 -0.203548 -0.189368
27   2.064833 -0.202288 -0.189368
28  -0.824589  0.331078  1.458932
29   0.154876 -0.200188 -0.189368
..        ...       ...       ...
327  2.260726 -0.203548 -0.189306
328 -0.824589 -0.202288 -0.186835
329 -0.579722 -0.202708 -0.189368
330 -0.530749 -0.201448 -0.189368
331  2.407645 -0.189689 -0.189368
332  0.203849 -0.203128 -0.188123
333 -0.481776  0.143770 -0.189368
334  1.428180 -0.200608 -0.189368
335 -0.481776 -0.202708 -0.189368
336 -0.824589 -0.202708 -0.188431
337  0.350769 -0.041439 -0.189368
338 -1.118428 -0.173730 -0.121385
339 -0.922535 -0.201448 -0.183868
340 -1.069455 -0.056978  0.084298
341  0.301796 -0.027579 -0.186754
342 -0.726642 -0.203548 -0.189368
343 -0.824589 -0.203548 -0.189057
344 -1.020482 -0.173730 -0.066034
345  0.350769 -0.191369 -0.189368
346  0.399742  1.542280  7.576443
347 -0.481776 -0.095195 -0.189368
348 -0.481776 -0.197248 -0.189368
349  0.644609 -0.052778  0.395288
350  1.379207 -0.201448 -0.189368
351 -0.481776 -0.186329 -0.189368
352  0.154876 -0.203128 -0.188730
353 -0.824589 -0.201028 -0.188715
354 -0.481776  0.003919 -0.189368
355 -0.481776 -0.195569 -0.189368
356 -0.481776 -0.059917 -0.189368

[357 rows x 3 columns]

##  22.3.5.	K-means 聚类最优 K 值选择

In [40]:
import numpy as np
from sklearn.cluster import KMeans

# 设置模型参数，其中 n_cluster 为类别的个数，并开始训练。

model = KMeans(n_clusters = 8)
model.fit(data_scale)

# 对每一类用户分别算出其 R、F、M 指标的相应平均值，高于平均值则赋值为 1，低于平均值则赋值为 0,R 指标则相反。

avg_RFM = [np.mean(data_scale.R),np.mean(data_scale.F), np.mean(data_scale.M)] 
RFM = pd.DataFrame()
RFM['R_type'] = ['1' if value[0] <= avg_RFM[0] else '0' 
                    for value in model.cluster_centers_]
RFM['F_type'] = ['1' if value[1] >= avg_RFM[0] else '0' 
                    for value in model.cluster_centers_]
RFM['M_type'] = ['1' if value[2] >= avg_RFM[0] else '0' 
                    for value in model.cluster_centers_]

# 将 RFM 三个指标连接起来。

RFM['RFM'] = RFM.R_type + RFM.F_type + RFM.M_type

# 最后，得到每个用户通过聚类模型预测的类型结果。

data.ix[data.TRANS_NUM > 0,['RFM']] = [RFM.ix[i,'RFM']  for i in model.labels_]

In [42]:
RFM

  R_type F_type M_type  RFM
0      0      0      0  000
1      1      0      0  100
2      1      1      0  110
3      0      1      1  011
4      0      0      0  000
5      1      1      1  111
6      1      1      1  111
7      1      1      1  111

In [44]:
data.RFM

0      000
1      000
2      000
3      000
4      000
5      000
6      000
7      000
8      000
9      000
10     000
11     000
12     000
13     000
14     000
15     100
16     000
17     100
18     000
19     000
20     000
21     100
22     000
23     100
24     000
25     000
26     000
27     000
28     000
29     000
      ...
970    000
971    000
972    000
973    000
974    000
975    000
976    000
977    000
978    000
979    000
980    000
981    000
982    000
983    000
984    100
985    000
986    100
987    000
988    000
989    000
990    000
991    000
992    000
993    000
994    100
995    000
996    000
997    000
998    100
999    100
Name: RFM, dtype: object